version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    open-pull-requests-limit: 20
    groups:
      aws_powertools:
        patterns:
          - "aws_powertools_logging_version"
          - "aws_powertools_metrics_version"
          - "aws_powertools_parameters_version"
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
