name: Daily Smoke Test

on:
  schedule:
    # Every weekday between 9 - 5 every 2 hours
    - cron: '0 9-17/2 * * 1-5'
  push:
  workflow_dispatch: # deploy manually

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Run Passport Smoke test against staging environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          CUCUMBER_PUBLISH_ENABLED: true
          coreStubUrl: ${{ secrets.PASSPORT_CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.PASSPORT_CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.PASSPORT_CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.ORCHESTRATOR_STUB_URL }}
        run: cd acceptance-tests && ./gradlew passportCriSmokeStaging

      - name: Get test results history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: LIME-Cucumber-gh-pages
          path: LIME-Cucumber-gh-pages

      - name: Cucumber HTML Report action
        uses: PavanMudigonda/html-reporter-github-pages@v1.3
        id: test-report
        if: always()
        with:
          test_results: acceptance-tests/target/cucumber-report
          gh_pages: LIME-Cucumber-gh-pages
          results_history: acceptance-tests/results-history

      - name: Publish Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: LIME-Cucumber-gh-pages
          publish_dir: acceptance-tests/results-history
          keep_files: true
