name: Pre-merge checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  style-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'
      - name: Run Spotless
        run: ./gradlew --no-daemon spotlessCheck

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Run Build
        run: ./gradlew --parallel build -x test -x spotlessApply -x spotlessCheck

  run-unit-tests:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            .gradle/
            */build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Run Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --parallel test jacocoTestReport -x spotlessApply -x spotlessCheck
      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: unit-test-reports
          path: |
            */build/reports/
          retention-days: 5
      - name: Cache Unit Test Reports
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-unit-test-reports-${{ github.sha }}
          path: |
            */build/jacoco/
            */build/reports/

  run-sonar-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'
#      - name: Generate Dependency Check Analyze Report
#        run: ./gradlew dependencyCheckAnalyze
      - name: Generate Aggregate Coverage Report
        run: ./gradlew report
      - name: Run SonarCloud Analysis
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -x test -x spotlessApply -x spotlessCheck
